// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTTz7-y4PsjmmZI2FXp2z8t0uH4vI5wpo',
    appId: '1:326437288177:web:0a86d284c99cf33ab71150',
    messagingSenderId: '326437288177',
    projectId: 'intelligent-notebook',
    authDomain: 'intelligent-notebook.firebaseapp.com',
    storageBucket: 'intelligent-notebook.firebasestorage.app',
    measurementId: 'G-GX4Q8TMPRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcOFRhgFeQodVxEpoFo-wv3wJvmaNwXDw',
    appId: '1:326437288177:android:a50df870890c38d7b71150',
    messagingSenderId: '326437288177',
    projectId: 'intelligent-notebook',
    storageBucket: 'intelligent-notebook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3eoHkS2uJiL9zUHssYFqVKQ0-vN2ours',
    appId: '1:326437288177:ios:ffd9c0ec0e5194f3b71150',
    messagingSenderId: '326437288177',
    projectId: 'intelligent-notebook',
    storageBucket: 'intelligent-notebook.firebasestorage.app',
    iosBundleId: 'com.nrd.intelligentNotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3eoHkS2uJiL9zUHssYFqVKQ0-vN2ours',
    appId: '1:326437288177:ios:ffd9c0ec0e5194f3b71150',
    messagingSenderId: '326437288177',
    projectId: 'intelligent-notebook',
    storageBucket: 'intelligent-notebook.firebasestorage.app',
    iosBundleId: 'com.nrd.intelligentNotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTTz7-y4PsjmmZI2FXp2z8t0uH4vI5wpo',
    appId: '1:326437288177:web:0584039d72d1ce75b71150',
    messagingSenderId: '326437288177',
    projectId: 'intelligent-notebook',
    authDomain: 'intelligent-notebook.firebaseapp.com',
    storageBucket: 'intelligent-notebook.firebasestorage.app',
    measurementId: 'G-FQSRV5XS5N',
  );
}
